libraryApp/urls.py
from django.urls import path
from django.conf.urls import url
from . import views 
from django.contrib.auth import views as auth_views
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from . import views
app_name = 'libraryApp'

urlpatterns = [
	path('',views.listWriters,name='writers'),
    path('d/<int:writer_id>',views.writerDetails,name='detail'),
	path('d/<bookName>',views.bookDetails,name='bookdetail'),
	path('signup', views.signup, name='signup'),
	path('login', auth_views.login, {'template_name': 'login.html'}, name='login'),
    path('logout', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
	
]

libraryApp/models.py
from audioop import reverse
from django.contrib.auth.models import User
from django.db import models
from datetime import date


class writer(models.Model):
   writer_id=models.AutoField(primary_key=True)
   writer_name=models.CharField(max_length=100)
   writer_dob=models.DateField()
   writer_dod=models.DateField('died',null=True, blank=True)
   writer_contact=models.CharField(max_length=100)
   writer_bio=models.TextField()
   writer_image=models.ImageField(upload_to='libraryApp/static/images', blank=True)
   def __str__(self):
       return self.writer_name

class book(models.Model):
    book_id=models.AutoField(primary_key=True)
    book_name=models.CharField(max_length=100)
    book_pubdate=models.DateField()
    book_summary=models.TextField()
    book_country=models.CharField(max_length=100)
    book_link=models.CharField(max_length=100)
    bwriter_id=models.ForeignKey('writer', on_delete=models.CASCADE)
    def __str__(self):
        return self.book_name

libraryApp/views.py
from django.shortcuts import render,redirect
from .models import writer,book
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def listWriters(request):
    writerList = writer.objects.all()
    return render(request, 'writerList.html',{'writer_list': writerList})

def writerDetails(request,writer_id):
    writerDetails = writer.objects.get(pk=writer_id)
    return render(request,'writerDetails.html',{'details':writerDetails})


def bookDetails(request,bookName):
    bookDetails = book.objects.get(book_name=bookName)
    return render(request,'bookDetails.html',{'bookDetails':bookDetails})


    #signup
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('users_uname')
            raw_password = form.cleaned_data.get('users_password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return render(request,'writerList.html',{'userName':username})#redirect('writerList')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

libraryApp/templates/bookDetails.html
{% extends "common.html"%}
{%block body%} 

<div id="dDiv">
<ul >

    <li id="details">
        <h2>{{bookDetails.book_name}}</h2>
        <div id="spanDetails">
        <h4>Published at {{bookDetails.book_pubdate}}</h4>
        <h4>Summary {{bookDetails.book_summary}}</h4>
        <h4>Country {{bookDetails.book_country}}</h4>
        <h4>Link <a href="{{bookDetails.book_link}}">Read Book</a></h4>
        
</div>
    </li>
  
</div> 

    
   
</ul>
{%endblock%}

                       

libraryApp/templates/common.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Library</title>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="{%static "css/style.css"%}">
<style>

#details
{
    position: absolute;
    top:300px;
  
    
}
#dDiv{
  margin-left: 300px;
}
#spanDetails{
  padding-left: 20px;
  width:300px;
}

</style>
</head>
<body>
<div id="header">
  
  <div class="section"> <span id="ribbon"></span> <span id="button"></span>
    
    <div>
      <div id="logo"><a href=""><img id="logoimg" src="{%static "images/logo.png"%}" alt=""></a></div>
      <div id="navigation">
        <ul class="primary">
          <li class="current"><a href="">Home</a></li>
          <li><a href="">About us</a></li>
          <li><a href="">Join us</a></li>
          <li><a href="">Contact us</a></li>
        </ul>
        <ul class="secondary">
          <li><a></a></li>
          
        </ul>
        
      </div>
      <h1>Hello</h1>
    </div>
  </div>
  <span id="tagline"></span>
  
 
  <div id="featured">
    {% block body %}body{% endblock %} 
  
         
  </div>
</div>

<div id="footer">
  <p>Copyright &copy; <a href="">ourTeam</p>
</div>
</body>
</html>

libraryApp/templates/login.html
{% load static %}
<html>
<head>
<title>LogIn</title>

<link rel="stylesheet" type="text/css" href="{%static "css/login.css"%}">
</head>

<body>
  <div class="title"><h2>Login</h2></div>
  
 
<div>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
</div>
</body>

</html>

libraryApp/templates/writerDetails.html
{% extends "common.html"%}
{%block body%} 

<div id="dDiv">
<ul >

    <li id="details">
        <h2>{{details.writer_name}} </h2>
        <div><span></span><a href="#"></a><img src='/{{details.writer_image}}' alt="Writer image" width="250" height="240"></div>
        <h4>Born at {{details.writer_dob}}</h4>
        <h4>Died at {{details.writer_dod}}</h4>
        <h4>Contact {{details.writer_contact}}</h4>
        
        {% for book in details.book_set.all%}
            Books <a href="{{book.book_name}}">{{book.book_name}}</a>
        {%endfor%}
        <h4>Bio {{details.writer_bio}}</h4>
    </li>
  
</div> 

    
   
</ul>
{%endblock%}

libraryApp/templates/writerList.html
{% extends "common.html"%}
{%block body%} 

<ul>
    {% for writer in writer_list %}

    <li class="first">
        <h2><a href="d/{{writer.writer_id}}">{{ writer.writer_name }}</a></h2>
        <div><span></span><a href="#"></a><img src='/{{writer.writer_image}}' alt="Writer image" width=250 height="240"></a></div>
        <a href="d/{{writer.writer_id}}" class="view"><span>View Details</span></a> 
    </li>
    {% endfor %}
</ul>
{%endblock%}